version: 1.0.{build}
image: WMF 5
clone_folder: c:\Remove-EmptyFolders

build:
  verbosity: minimal

install:
  - cinst pester

build_script:
  - ps: Write-Host $Env:APPVEYOR_BUILD_FOLDER
  
test_script:
  - ps: $res = Invoke-Pester -Path "c:\Remove-EmptyFolders" -OutputFormat NUnitXml -OutputFile c:\Remove-EmptyFolders\TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path c:\Remove-EmptyFolders\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
